sudo: false  # Use container-based infrastructure
language: python
dist: trusty
python:
  - "2.7"
  - "3.6"
git:
  # don't need the default depth of 50
  # but don't want to use a depth of 1 since that affects
  # whether jobs run when you have multiple commits queued
  # https://github.com/travis-ci/travis-ci/issues/4575
  depth: 10
cache:
  pip: true
  # cache directory used for Ensembl downloads of GTF and FASTA files
  # along with the indexed db of intervals and ID mappings and pickles
  # of sequence dictionaries. Also, pip
  directories:
    - $HOME/.cache/pyensembl/
addons:
  apt:
    packages:
      # Needed for NetMHC
      - tcsh
env:
  global:
    # MHC_BUNDLE_PASS
    - secure: "TLTzSIABO/iYke8C66c0PRaWDZ5lx90s8XimSfDONOTXaX74V25O65qxzIWPAihxcdfLYA+bE2YRsjYOtuK+6DB2vjXbmoCQAXIFT/QXz4+iZTxN3g/s5N4hIR8tf9MSQ3KdNHOw7lKzdgAWKsFDQ8vwrqzYUNJGVtvoQSWCmPw="
before_install:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - python --version
  # install MHC predictors
  - git clone https://mhcbundle:$MHC_BUNDLE_PASS@github.com/openvax/netmhc-bundle.git
  - export NETMHC_BUNDLE_HOME=$PWD/netmhc-bundle
  - mkdir tmp
  - export NETMHC_BUNDLE_TMPDIR=$PWD/tmp
  - export PATH=$PATH:$NETMHC_BUNDLE_HOME/bin
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      numpy nose pandas pandoc
  - source activate test-environment
  - pip install pypandoc
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
  - pyensembl install --release 75 --species human
  - pyensembl install --release 87 --species human
script:
  - ./lint.sh
  - nosetests test --with-coverage --cover-package=topiary
after_success:
  coveralls
deploy:
  provider: pypi
  distributions: sdist
  user: openvax
  password: # See http://docs.travis-ci.com/user/encryption-keys/
    secure: "S4KWAhJpKYx5F/cBc6cf9GCZ8Hd+WtMA6V6PP25PglLnVaXrxB5QxuAIWGAvr/jGuTHjfCSCNDwTptW3natLjJR9IfJdJPp3gNvM0RDjWY4FsziFz/nG/bZo9qnh4ZCDhK/Po1izxXM0u9z6gUc0U2iKK1ZSdfawyW4nZbAXQUU="
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"

